### ISSUE TITLE
Too many dependencies in requirements.txt

### ISSUE THREAD

**Issue by silverhairs** [CedricMurairi/flask_messenger#4]
Hey, cool project but the requirements.txt contains too many dependencies, and most of them are not used in the project, this makes the app very heavy and it may run very slow. It took me around 5min to install the requirements before realizing that.
I would suggest using a virtual environment like [pipenv](https://pypi.org/project/pipenv/) or [virtualenv](https://pypi.org/project/virtualenv/).

**Comment by CedricMurairi** [comment]
Hey, thanks man for the comment, I mean I made a big mistake maybe when
freezing my requirement.txt, there should be something wrong.
However, I appreciate your feedback and will fix everything and merge your
changes, I have to change the idea though; I want to make it kind of a
single page application I think I will be shipping the MVP by Wednesday,
your contribution is welcome.
We might definitely discuss the idea together if you do not mind.

*Cedric Murairi*
*Student at African Leadership University*
Computer Science 2019 - 2023
Aspiring Software Engineer, aiming at AI and ML

2nd Floor | Kigali Heights
Kigali | Rwanda
*c.murairi@alustudent.com* <c.murairi@alustudent.com>
+250 (0) 787914985
+243 (0) 974261829
*www.alueducation.com <http://www.alueducation.com> | We are hiring
<https://alueducation.com/careers/>*
*Facebook <https://www.facebook.com/alu.education> | Twitter
<https://twitter.com/ALU_education> | Instagram
<https://www.instagram.com/alueducation/>*


Le dim. 5 juil. 2020 à 23:51, Boris Kayi <notifications@github.com> a
écrit :

**Comment by silverhairs** [comment]
> Hey, thanks man for the comment, I mean I made a big mistake maybe when freezing my requirement.txt, there should be something wrong. However, I appreciate your feedback and will fix everything and merge your changes, I have to change the idea though; I want to make it kind of a single page application I think I will be shipping the MVP by Wednesday, your contribution is welcome. We might definitely discuss the idea together if you do not mind.

Awesome
